### ISSUE TITLE
`spautor(..., spcov_type = "none")` error

### ISSUE THREAD

**Issue by henryrscharf** [USEPA/spmodel#27]
Hi @michaeldumelle,

I've got another very small issue for you...

I was planning to have students in my class compare model fit statistics for some SAR/CAR fits, including the classical case of iid errors. To make it easy to compute AIC and AICc for a traditional `lm()` style fit, it's nice to have it as an `spautor` type object so it can be passed to, e.g., `AIC()` along with spatial models. 

I was trying this out myself and noticed that a call to `spautor(..., spcov_type = "none")` throws an error. Looks like this combination of arguments gets caught by `spgautor_checks()`. Anyway, I thought it might be useful for such a function call to return the usual lm fit rather than an error just for consistency of notation. I know I can get what I'm after using `splm(..., spcov_type = "none")`, but it feels 'wrong', given the areal index :). It looks like I can also get around the issue with some explicit `spcov_initial()` arguments, so I could use that approach if there's a reason you want to prevent `spautor(..., spcov_type = "none")`.

Thanks,
Henry

**Comment by michaeldumelle** [comment]
@henryrscharf I am happy to add this! I will update here when it is done; may take a bit of time as it is behind some other things in the queue and will require a bit of thought.

Thanks for the suggestion!

**Comment by henryrscharf** [comment]
Thanks very much!

**Comment by michaeldumelle** [comment]
@henryrscharf this request has been implemented on the development version, which you can download by running

```r
remotes::install_github("USEPA/spmodel", ref = "develop")
```

``` r
library(spmodel)
packageVersion("spmodel")
#> [1] '0.10.0'
```

<sup>Created on 2024-11-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


The fix I implemented was to (under the hood) call `splm()` when `spautor(..., spcov_type = "none")`. As a result, the output object has class `splm()`:

``` r
splm(
  formula = log_trend ~ stock,
  data = seal,
  spcov_type = "none"
)
#> 
#> Call:
#> splm(formula = log_trend ~ stock, data = seal, spcov_type = "none")
#> 
#> 
#> Coefficients (fixed):
#> (Intercept)      stock10  
#>    -0.07916      0.09327  
#> 
#> 
#> Coefficients (none spatial covariance):
#>      ie  
#> 0.02515
spautor(
  formula = log_trend ~ stock,
  data = seal,
  spcov_type = "none"
)
#> 
#> Call:
#> splm(formula = log_trend ~ stock, data = seal, spcov_type = "none")
#> 
#> 
#> Coefficients (fixed):
#> (Intercept)      stock10  
#>    -0.07916      0.09327  
#> 
#> 
#> Coefficients (none spatial covariance):
#>      ie  
#> 0.02515
spautor(
  formula = log_trend ~ stock,
  data = seal,
  spcov_type = "car"
)
#> 
#> Call:
#> spautor(formula = log_trend ~ stock, data = seal, spcov_type = "car")
#> 
#> 
#> Coefficients (fixed):
#> (Intercept)      stock10  
#>    -0.06694      0.08880  
#> 
#> 
#> Coefficients (car spatial covariance):
#>      de    range    extra  
#> 0.04880  0.43432  0.01957
```

<sup>Created on 2024-11-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


I decided that handling it this way prioritized transparency, though it may feel a bit awkward if using something like `update()`.

If called as part of a vector format, however, the global object still has class `spautor_list`, while each element has either class `splm()` or `spautor()`, depending on spatial covariance type:

``` r
spgmods <- spautor(
  formula = log_trend ~ stock,
  data = seal,
  spcov_type = c("none", "car")
)
spgmods
#> $none
#> 
#> Call:
#> splm(formula = log_trend ~ stock, data = seal, spcov_type = "none")
#> 
#> 
#> Coefficients (fixed):
#> (Intercept)      stock10  
#>    -0.07916      0.09327  
#> 
#> 
#> Coefficients (none spatial covariance):
#>      ie  
#> 0.02515  
#> 
#> 
#> $car
#> 
#> Call:
#> spautor(formula = log_trend ~ stock, data = seal, spcov_type = "car")
#> 
#> 
#> Coefficients (fixed):
#> (Intercept)      stock10  
#>    -0.06694      0.08880  
#> 
#> 
#> Coefficients (car spatial covariance):
#>      de    range    extra  
#> 0.04880  0.43432  0.01957  
#> 
#> 
#> attr(,"class")
#> [1] "spautor_list"
glances(spgmods)
#> # A tibble: 2 × 11
#>   model     n     p  npar value   AIC  AICc   BIC logLik deviance pseudo.r.squared
#>   <chr> <int> <dbl> <int> <dbl> <dbl> <dbl> <dbl>  <dbl>    <dbl>            <dbl>
#> 1 car      94     2     3 -74.9 -68.9 -68.7 -61.3   37.5     92.5           0.0573
#> 2 none     94     2     1 -69.1 -67.1 -67.1 -64.6   34.6     92             0.0754
```

<sup>Created on 2024-11-23 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>


Analogous changes were made for `spgautor()` and `spautorRF()` as well as for the `spcov_initial` argument to these functions (when relevant). This should be part of the next CRAN submission (likely v0.10.0).

Thanks again for the suggestion and let me know if you have any questions!

**Comment by michaeldumelle** [comment]
@henryrscharf this is now on CRAN as part of version 0.10.0 (see NEWS [at this link](https://cran.r-project.org/web/packages/spmodel/news/news.html)).
