### ISSUE TITLE
robust semivariogram

### ISSUE THREAD

**Issue by mgm-cincy-epa** [USEPA/spmodel#28]
Could you please consider adding a robust semivariogram as an option with the empirical semivariogram (esv) function?
Thanks,
Mike

**Comment by michaeldumelle** [comment]
Thanks @mgm-cincy-epa ! We can certainly add this -- probably sometime early 2025. I will update here when this is ready on the development version

**Comment by michaeldumelle** [comment]
@mgm-cincy-epa we have added the `robust` argument to `esv()` (the default is `FALSE`). You can try it out by installing the development version:

```r
remotes::install_github("USEPA/spmodel", ref = "develop")
library(spmodel)
esv(sulfate ~ 1, sulfate, robust = TRUE)
```

Thanks for the suggestion!

**Comment by michaeldumelle** [comment]
@mgm-cincy-epa this is now on CRAN as part of version 0.10.0 (see NEWS [at this link](https://cran.r-project.org/web/packages/spmodel/news/news.html)).
