### ISSUE TITLE
What are de and ie in the result of the function varcopm

### ISSUE THREAD

**Issue by ManuelSpinola** [USEPA/spmodel#30]
In the function uarcomp, what de and ie means?

**Comment by michaeldumelle** [comment]
@ManuelSpinola Thanks for the question.

The first paragraph of the details section in the [`splm()` documentation](https://usepa.github.io/spmodel/reference/splm.html) describes `de` and `ie`. They are described in more detail in the "Spatial Linear Models" section of the [technical details vignette](https://usepa.github.io/spmodel/articles/technical.html). We can also add some clarity regarding these parameters to the `varcomp()` documentation in the next CRAN version.
